### ISSUE TITLE
Condensation+DewPoint+RH+Temperature on construction layers

### ISSUE THREAD

**Issue by ayezioro** [ladybug-tools/honeybee-legacy#571]
Hi,
Inspired by Chris's webinar on THERM I've written a component that calculates what's in the subject of the issue.
Of course it is based on steady state equations. I will ask your opinion about it.
Right now it has many outputs. Some of them can be cleared. But for now is WIP.
I intend for the next stage to draw the section of the wall/roof/floor with the lines connecting the results.
Also there is something i don't know how to deal with right now: Vapour moisture. If you have ideas about that please do tell.
The component is located on the WIP section mainly because i'm not sure what is the preferable location. probably section 6-Construction.
This is the example that you can check:
https://www.dropbox.com/s/wm6u7dk575r7f06/TemperatureGradient%2BDewPointCalculator%2BCondensation_for%20DB.gh?dl=0
Please let me know your thoughts.
Thanks,
-A.

**Comment by chriswmackey** [comment]
@ayezioro ,

I just took a look at the dropbox link and this looks great!  We're slowly making our way into the capabilities of WUFI now!

Because the component takes inputs inputs of EP Constructions, I think you are right that the 6-Construction tab is the most appropriate place.  Still, you should be aware of a number of other components that calculate similar results in different tabs: The "Ladybug_Steady State Surface Temperature" component and @AntonelloDN 's "Ladybug_Wet Bulb Temp" component.  I think it's fine that these components serve separate purposes and use separate code for now but we should keep the fact that these components share similar underlying functions in mind when we start to clean up Ladybug/Honeybee.

You should send a pull request whenever you like and we'll merge it in.  Some visuals of line graphics would be great!  As for vapor moisture transmission, it sounds like you would need a transient simulation to make those values meaningful, no?  Maybe we should leave that variable out for now while the calculation is steady state (E+ materials don't have vapor transmission properties anyway).  Or perhaps you give users the options to put in a vapor barrier somewhere in the construction and just assume that this blocks all moisture transmission.

Thanks again, @ayezioro !
-Chris

**Comment by ayezioro** [comment]
Hi Chris,
Thanks.
As for the vapor moisture you are right. No properties for that in EP materials, and that's the main obstacle. I've found some equations to calculate (for steady state) the moisture value, but without the properties it will be cumbersome to deal with that. So i agree to leave it as is. Maybe i'll provide the location of the vapor barrier in the graphics. I'll see.
I'm waiting Arpan will upload the video of your last webinar so i can finally get how to manage with the github :-). I was present on the live broadcast but needed to do other tasks during most of the webinar (sorry).
I'll also check what is in the other components that can be similar and unified as for the equations.
-A.

**Comment by ayezioro** [comment]
Hi Chris,
I'm going to ask for a bit of assistance.
Find this updated example:
https://www.dropbox.com/s/wm6u7dk575r7f06/TemperatureGradient%2BDewPointCalculator%2BCondensation_for%20DB.gh?dl=0
The wall is drawn and the result lines too.
I want to know if there is a way of getting the lines with some thickness and color if the polyline is not closed. I can do that for the wall layers since they are closed. In the example i use Human components and also give an output for the color of the lines. So i wonder if there is a better way.
Want to ask also about text. I want to plot "many" things, and wonder again if with the whole refurbish of the components you can make my process shorter.
Of course i'll be glad to get your opinion on how it is shown right now, specially regarding the size of the wall section.
Thanks,
-A.

**Comment by ayezioro** [comment]
Hi,
As for the text i managed, so no need to reply to this respect.
The example was updated and can be found at the link above. I'll be glad to hear your opinions.
There are some issues to be solved: Section for different situations (wall, roof, floor), Rh/Temp scales.
I'm in doubt if plotting the results as text will be good/nice or just to "be happy" with the panel outputs.
Thanks,
-A.

**Comment by ayezioro** [comment]
Almost ready!
Texts are there. Please check the example file for remarks.
Need to solve the bake option. Not addressed at all. Any help will be appreciated (to make the path shorter ...).
Need to solve the drawing of roofs/floors. Right now everything is drawn as walls (vertical).
Need to consider a new scale axis for DewPoint. For unusual cases the line falls below the wall section.
Any remarks?
-A.

**Comment by ayezioro** [comment]
Bake solved ... thank God!
Just a question: When bake == 2, it is supposed to bake meshes. In  my case it bakes only curves. Do you mind to have a look?
The roof/floor cases are drawn as in walls, though the calculation is fine. Is just a cosmetic issue that i'll address soon. For now i'll commit the component AFTER the above bake explanation.
As usual, please check the dropbox example.
Thanks,
-A.

**Comment by chriswmackey** [comment]
@ayezioro ,

I apologize for such a late response on this one. I will check the uploaded file as soon as I get the chance, which should be sometime later today.  I am sure that we can figure out the bake issue quickly and I'll try to give feedback on the other features.

-Chris

**Comment by chriswmackey** [comment]
@ayezioro ,

Sorry that it took so long for me to check this.  The component is looking really good.  I'm realizing how useful the visual output is not just for understanding temperature gradients and condensation but also just understanding what the constructions look like and doing visual comparisons between constructions.  

The bakeIt option seems to be working well as you said.  I have a few comments / suggestions:

1) I understand what you are trying to do with the thick black mesh lines but they seem to be hurting a bit more than they are helping.  In 3D Perspective mode, they are displaying on top of each other like so:
![meshesontopofeachother](https://cloud.githubusercontent.com/assets/5567574/20635769/bd3231b4-b32f-11e6-8f65-031301e67bd0.JPG)
I also see that, when you set bakeIt to True, you are baking these as actual curves, which displays a lot better.  I think that you should consider doing the same for the GH component outputs even though I know that the default GH line color is not black.  People can preview them black if you output them as actual curves, especially if these curves have their own designated output.  Outputting them like this will also give people the option of setting the line weights to what they want with the Human component.

2) I don't know what is determining the colors of the materials currently but it would be nice if all of the colors of the different materials are different so that we can distinguish them more easily.  This also would make a color key for the materials more meaningful and could avoid the current situation where the user has to relate colors to numbers and then numbers to material names.  In an ideal case, there would be a way to manually assign custom material colors and the default might use a randomly-generated color set or one of the default Ladybug color sets in order to ensure that the colors are different.

3) It would be so nice to have a legendPar input for the component, even though I know that it won't be used in the same way that it is on a lot of other visual components.  It would just be great to adjust the upper and lower boundaries of temperature with the lowB and highB.  Also, the legendPar colors could be used to color the materials.  Alternatively, the legendPar colors could be used for coloring the output lines and you can have a separate input for material colors.

4) It is not immediately clear which lines correspond to temperature and humidity.  I actually don't know what the 3rd line is telling me as it seems to be neither dewPoint nor dryBulbTemperature.  A legend for this or at least some full descriptions on the component outouts would be helpful.

-Chris

**Comment by chriswmackey** [comment]
@ayezioro ,

I know that it's been a while since you worked on this component but it would be great to have this available for the upcoming release at least in the WIP section.  To say the least, it is very useful to have a component that converts the constructions in the library to geometry that is ready for THERM workflows.  We can leave the component in WIP until we figure out a good way to deal with the lack of vapor permeability in the materials.

Would you be ok with integrating this in the WIP section of the upcoming release?  If so, would you be able to send a pull request before this Friday?  I am also happy to help format it for the release if it will take time to send the pull request.

-Chris

**Comment by chriswmackey** [comment]
I should also mention that the deadline for the next stable release is this Friday (the 28th).

**Comment by ayezioro** [comment]
Hi @chriswmackey,
No problem in committing but ... since last time i wrote here (a while ago) i didn't touched the code. I "broke" with your suggestion of the legend. Have the intention to get back though.
If this is fine with you, i'll commit it AS IS.

I'll write you an email to ask about technicalities of github (ashamed to ask here ... :-()
-A.

**Comment by chriswmackey** [comment]
@ayezioro ,

Comitting "As Is" is perfectly fine.  We'll just add it to the WIP section for now until we clean it up.  I'll keep a look out four your pull request.

-Chris

**Comment by ayezioro** [comment]
@chriswmackey,
Commited and sent a pull request.
Hope it is fine.
-A.

**Comment by chriswmackey** [comment]
Received!

**Comment by devngc** [comment]
@chriswmackey,
Can you please close this if this is already implemented?

**Comment by chriswmackey** [comment]
Will do. FYI, I have implemented some better functions for getting temperature profiles of constructions in the honeybee-energy library for Honeybee[+]. The nice thing is that I have methods that work for both [Opaque Constructions](https://github.com/ladybug-tools/honeybee-energy/blob/master/honeybee_energy/construction/opaque.py#L100-L131) and for [Window Constructions](https://github.com/ladybug-tools/honeybee-energy/blob/master/honeybee_energy/construction/window.py#L245-L275), the latter of which was a lot more difficult to implement than I ever realized. We should be able to use these to make some nice visualizations in HB[+}.
