### ISSUE TITLE
Missing NormbyFloorArea in Honeybee Read EP Results component

### ISSUE THREAD

**Issue by jarjarven** [ladybug-tools/honeybee-legacy#742]
Hi, all,
I am doing honeybee energy simulation following Chris's guiding videos. However, when I tried to use the Honeybee Read EP Results component, I found that the option called NormbyFloorArea was missing. I checked that my component version was 0.0.65 Jan_01_2020 while the one used by Chris in his video was 0.0.55 Sep_11_2014. I wonder if the way of doing it has been changed in the newest updates? How could I get the results norm by floor area?

Jarven

**Comment by jarjarven** [comment]
@mostaphaRoudsari @chriswmackey

**Comment by chriswmackey** [comment]
@jarjarven ,

This issue is happening because honeybee isn't able to load up the schedules from the OpenStudioMasterTemplate.idf:

![image](https://user-images.githubusercontent.com/5567574/79141499-ec7ea080-7d87-11ea-920b-ba8b56b092ae.png)

Make sure you have that file there and, if it isn't able to automatically download, try manually replacing it using the file here:
https://github.com/ladybug-tools/honeybee-legacy/blob/master/resources/OpenStudioMasterTemplate.idf

**Comment by chriswmackey** [comment]
@jarjarven ,

The ability to normalize results by floor area has been pulled out into another component "Honeybee_Normalize Data by Floor Area":
![image](https://user-images.githubusercontent.com/5567574/79142149-0a003a00-7d89-11ea-8211-16809c2234a0.png)


Questions like this that are not bugs in the software should be posted to the forum:
https://discourse.ladybug.tools/

**Comment by jarjarven** [comment]
@chriswmackey 

I see. Thank you so much, Chris.
