### ISSUE TITLE
Failed to find  schedules in the Honeybee schedule library

### ISSUE THREAD

**Issue by roxas358** [ladybug-tools/honeybee-legacy#743]
I got the error running honeybee energy simulation.   Is there anyone know what to do?
And what is the folder of the Honeybee schedule library file?
10. Failed to find MEDIUM OFFICE BLDG OCC in the Honeybee schedule library.
11. Failed to find MEDIUM OFFICE HTGSETP in the Honeybee schedule library.
12. Failed to find OFFICE BLDG LIGHT in the Honeybee schedule library.
13. Failed to find MEDIUM OFFICE CLGSETP in the Honeybee schedule library.
14. Failed to find MEDIUM OFFICE BLDG EQUIP in the Honeybee schedule library.
15. Failed to find MEDIUM OFFICE ACTIVITY in the Honeybee schedule library.
16. Failed to find MEDIUM OFFICE INFIL QUARTER ON in the Honeybee schedule library.
17. Failed to find ALWAYS ON in the Honeybee schedule library.

**Comment by chriswmackey** [comment]
@jarjarven ,

This issue is happening because honeybee isn't able to load up the schedules from the OpenStudioMasterTemplate.idf:

![image](https://user-images.githubusercontent.com/5567574/79141499-ec7ea080-7d87-11ea-920b-ba8b56b092ae.png)

Make sure you have that file there and, if it isn't able to automatically download, try manually replacing it using the file here:
https://github.com/ladybug-tools/honeybee-legacy/blob/master/resources/OpenStudioMasterTemplate.idf

**Comment by roxas358** [comment]
Super thanks！

**Comment by roxas358** [comment]
@chriswmackey 
Super thanks！
